# Generated by Django 3.0.4 on 2020-03-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_auto_20200322_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default='', verbose_name='Question'),
            preserve_default=False,
        ),
    ]
