# Generated by Django 3.0.4 on 2020-03-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0010_auto_20200322_0551'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'answer', 'response')},
        ),
    ]
